# Generated by Django 4.1.4 on 2022-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='client_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scopes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_uri',
            field=models.TextField(blank=True),
        ),
    ]
