# Generated by Django 4.1.4 on 2022-12-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_user_client_id_user_client_secret_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
